### ISSUE TITLE
Using Claude in LangChain

### ISSUE THREAD

**Issue by mbdzi** [anthropics/anthropic-sdk-python#21]
Does anyone know if it is possible to use Claude for document question and answering in LangChain?

The Claude LLM model is integrated to LangChain. What is missing: LangChain-compatible Claude embeddings.

Does anyone know how I can generate them? Or alternative routes I could take to get Claude to work with Langchain document question and answering?

**Comment by mikelambert** [comment]
We have a LLMModel and ChatModel (coming this weekend) in LangChain.

We do not have embeddings, but that's because we do not currently expose a server API for embeddings as of April.

You're welcome to sub in any other embedding model you like for now. I believe langchain separates `Embeddings` from `LLMModel` and lets you plug-n-play, so you should be able to use any of the `Embeddings` modules supported by langchain.
