### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

### ISSUE THREAD

**Issue by supreetkt** [anthropics/anthropic-sdk-python#280]
While using the latest version of anthropic, I'm seeing the above error. I used traceback and its root cause seems to be the tokenizer package:

`line 19, in <module>\n    from anthropic import AuthenticationError, NotFoundError\n  File \"/opt/python/anthropic/__init__.py\", line 6, in <module>\n    from ._client import (\n  File \"/opt/python/anthropic/_client.py\", line 10, in <module>\n    from tokenizers import Tokenizer  # type: ignore[import]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/python/tokenizers/__init__.py\", line 78, in <module>\n    from .tokenizers import (\nModuleNotFoundError: No module named 'tokenizers.tokenizers'\n`

Any ideas on how to resolve this?
I also opened an issue on tokenizers library: https://github.com/huggingface/tokenizers/issues/1416

Installed: `anthropic==0.7.8`, `tokenizers==0.15.0`

**Comment by rattrayalex** [comment]
Is it possible you have a local file called `tokenizers.py`, or similar?

**Comment by supreetkt** [comment]
No, that's not the right way to fix this I feel.. This issue also seems to occur for python 3.12, and not python 3.11

**Comment by rattrayalex** [comment]
cc @RobertCraigie any idea?

**Comment by RobertCraigie** [comment]
This is happening because `tokenizers` doesn't support Python 3.12 yet, https://github.com/huggingface/tokenizers/issues/1416#issuecomment-1859977789.

A fix for this will be included in the next release by deferring the `tokenizers` import so that you can still use the rest of the client with `3.12`. Note that you'll still get an error if you call `client.count_tokens()` or `client.get_tokenizer()`.
