### ISSUE TITLE
Unexpected failure when `None` is passed for optional API endpoints, due to `NotGiven` class

### ISSUE THREAD

**Issue by noahtren** [anthropics/anthropic-sdk-python#372]
I was surprised to see an error when creating a response like so
```python
resp = anthropic_client.messages.create(max_tokens=512,
                                        system=None,
                                        model='claude-3-sonnet-20240229',
                                        messages=[{'role': 'user', 'content': 'what is the sum of 2 and 2'}])
```
It works if I omit the system kwarg entirely. But it's generally intuitive to use None for higher-order functions where kwargs are optional, but it fails here.

I've not seen this kind of type before, and would've hoped that None would be available, too:
```python
system: str | NotGiven = NOT_GIVEN
```

**Comment by rattrayalex** [comment]
That's an interesting point, thanks for raising it. We'll discuss internally.

I assume you're doing this because you want a ternary there?

**Comment by noahtren** [comment]
Yes! This is my current workaround:

```python
def complete(messages, system=None):
  extra_kwargs = {"system": system} if system else {}
  resp = anthropic_client.messages.create(max_tokens=512,
                                          model='claude-3-sonnet-20240229',
                                          messages=messages,
                                          **extra_kwargs)
```

**Comment by rattrayalex** [comment]
Great. Your workaround looks appropriate - you could also do `system=True if system else NotGiven`, though I'm not sure we export that right now.

Upon discussion, we want `None` as a request param to consistently mean `null` in what is sent to the API (i.e., `"system": null` in the json request in this case), which is not what you want to do here - the API would reject that.

We'll look into exporting `NotGiven` so that you can do this more conveniently!

**Comment by rattrayalex** [comment]
Thanks for bringing this up. Upon further discussion, we've decided that we want to continue to have `None` mean sending `null` in the API, and since the API does not accept `system: null` right now, you won't be able to pass `system=None`.

However, [we did release `NOT_GIVEN` as an exported property in v0.19.2](https://github.com/anthropics/anthropic-sdk-python/pull/378), so you can at least still write an if-else expression.
