### ISSUE TITLE
Which Pydantic class to use for streaming messages?

### ISSUE THREAD

**Issue by ysolanky** [anthropics/anthropic-sdk-python#546]
Hello, 

I noticed some discrepancy while implementing message streaming. For example, the `MessageStopEvent` object actually returned by the API is different from the example in docs. 

[The docs](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/message_stop_event.py)
[What is actually returned from the api](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/lib/streaming/_types.py)

Which of these models for `MessageStopEvent` and the other pydantic models will be used in the future?

**Comment by RobertCraigie** [comment]
Hey @ysolanky, the SDK adds it's own types as we provide an [accumulation helper](https://github.com/anthropics/anthropic-sdk-python/blob/main/helpers.md) which is why the types are different.

The types you linked to [first](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/message_stop_event.py?rgh-link-date=2024-06-21T05%3A35%3A00Z) are exactly what the API returns, and are used by `client.messages.create()`.

The second types you [linked to](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/lib/streaming/_types.py?rgh-link-date=2024-06-21T05%3A35%3A00Z) are the ones returned by our SDK helper.

Does this make sense?
