### ISSUE TITLE
Feature request: tool_choice='none' for analysing available tools - but not using them

### ISSUE THREAD

**Issue by zby** [anthropics/anthropic-sdk-python#611]
In my workflow I ask the LLM to analyze the available tools before using them. It is useful to pass the list of tools in the same way as I pass it when I want it to use them - otherwise I need to render the schemas as text or json in the prompt itself.

This would be compatible with the OpenAI API which allows for this.

**Comment by stephaniepang97** [comment]
Hi, thanks for providing this feedback. Are you seeing a clear improvement by asking Claude to analyze the tools instead of just using them? Unfortunately this is not a priority for us at the moment because we expect users to not pass in `tools` if no tool use is desired. I would suggest utilizing [Chain of thought](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#chain-of-thought) for this (incompatible with the `tool_choice` param) or putting the tools into the prompt itself as you mentioned.
