### ISSUE TITLE
Iterable vs List in the request datatypes

### ISSUE THREAD

**Issue by adubovik** [anthropics/anthropic-sdk-python#656]
Consider the [definition](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/message_param.py#L17-L22) of `MessageParam`:

```python
class MessageParam(TypedDict, total=False):
    content: Required[
        Union[
            str, Iterable[Union[TextBlockParam, ImageBlockParam, ToolUseBlockParam, ToolResultBlockParam, ContentBlock]]
        ]
    ]
```

The `Iterable` here doesn't allow me to write any kind of useful transformations over the datatype without changing its state in the process:

```python
from anthropic.types import MessageParam

def transform(msg: MessageParam) -> MessageParam:
    content = msg["content"]
    if isinstance(content, str):
        return msg

    # Impossible:
    # print(len(content))
    # print(content[1])
    # print(content[1:])

    # Possible, but the original content is exhausted in the end
    # content_list = list(content)

    return msg
```

which is quite inconvenient and could easily lead to all kind of errors.

Is there any reason to use `Iterable` here and in other request/response datatypes?
Could it be replaced with `List`?

**Comment by RobertCraigie** [comment]
> Is there any reason to use Iterable here and in other request/response datatypes?
> Could it be replaced with List?

We use `Iterable` in these types because if it was `List` you'd run into annoying typing variance issues, here's an example:
```py
from typing import Iterable

def takes_list(x: list[str | int]) -> None: ...
def takes_iter(x: Iterable[str | int]) -> None: ...

a = ["foo"]
takes_list(a)  # error: Argument of type "list[str]" cannot be assigned to parameter "x" of type "list[str | int]"
takes_iter(a)  # no error!
```

> Possible, but the original content is exhausted in the end

Yeah it's unfortunate that the original message param content would be consumed, I think you have two options:
1. Make your `transform()` function mutative
2. Disallow one-shot iterables in your `transform()` function somehow

Does that help?

**Comment by adubovik** [comment]
@RobertCraigie thank you, the reason is clear now.

What about `Sequence`?

```python
from typing import Iterable, Sequence

def takes_list(x: list[str | int]) -> None: ...
def takes_iter(x: Iterable[str | int]) -> None: ...
def takes_sequence(x: Sequence[str | int]) -> None: ...

a = ["foo"]
takes_list(a)     # error: Argument of type "list[str]" cannot be assigned to parameter "x" of type "list[str | int]"
takes_iter(a)     # no error!
takes_sequence(a) # no error!
```

> I think you have two options

Well, I think I could insert assertions like `check_is_list(content)` in all of the relevant places, but it's rather unwieldy, error-prone, and hard to maintain.

There is another dangerous pitfall which I didn't mention before, but that was the reason I run into this Iterable conundrum in the first place.

I used Pydantic `BaseModel` as a container for `MessageParam` objects.
`BaseModel` object traverses in `__init__` its members along with their type schemes and does appropriate conversions. That is if `Iterable` is encountered, then the value will be [converted](https://github.com/pydantic/pydantic/blob/a031acd450da71fae356711f7bd58774d95c6569/pydantic/v1/fields.py#L965) to it via `iter()`:

```python
from pydantic import BaseModel # either v1 or v2
from typing_extensions import Iterable, TypedDict

class Wrapper1(TypedDict):
    elems: Iterable[int]

class Wrapper2(BaseModel):
    lst: Wrapper1

w = Wrapper2(lst={"elems": [1, 2, 3]})
print(type(w.lst["elems"]))  # <class 'list_iterator'>
```

So whenever one is using BaseModel as a container for Anthropic datatypes _(which is not that uncommon I imagine)_, this 
may result in tricky bugs e.g. two for-loops over the same Iterable lead to different results.

**Comment by RobertCraigie** [comment]
`Sequence` is an option, it does solve the type variance issue but in general we try to accept as broad of a type as possible in our params so users can pass whatever they like and `Sequence` is more constrained than `Iterable`.

Namely it'd also be a breaking change so if we do decide to change to `Sequence` it likely won't be shipped quickly unfortunately as some users may be relying on just being able to pass an iterable.

> BaseModel object traverses in __init__ its members along with their type schemes and does appropriate conversions. That is if Iterable is encountered, then the value will be [converted](https://github.com/pydantic/pydantic/blob/a031acd450da71fae356711f7bd58774d95c6569/pydantic/v1/fields.py#L965) to it via iter():

Thanks for raising, I agree that is not ideal. Additionally in Pydantic v2, there is a [bug](https://github.com/pydantic/pydantic/issues/9467) with `Iterable` handling so that doesn't even work at all right now...

Maybe a workaround for now would be to add a pydantic post-validator that turns `content` into a `list` so you don't have to handle the conversion everywhere? Sorry this is difficult!

**Comment by adubovik** [comment]
> Namely it'd also be a breaking change so if we do decide to change to Sequence it likely won't be shipped quickly unfortunately as some users may be relying on just being able to pass an iterable.

I feel the pain of breaking changes.
I wonder which use cases warrant the generality of iterable though...

> Maybe a workaround for now would be to add a pydantic post-validator that turns content into a list so you don't have to handle the conversion everywhere? Sorry this is difficult!

No worries, I've switched to `dataclasses`. Pydantic was an overkill in my case anyway.

Thank you for the prompt replies!

**Comment by RobertCraigie** [comment]
Thanks for your feedback! I've noted this down so we'll revisit in the future when we're making some other breaking changes.
